---
version: "3"

networks:
  default:
    name: showroom.example.com

services:

  web:
    # image: docker.io/httpd:2.4
    # image: docker.io/nginx
    image: registry.redhat.io/rhel9/nginx-122
    container_name: web
    hostname: web
    command: nginx -g "daemon off;"
    ports:
      # - "8000:80"
      - "8000:8080"
    volumes:
      # - "./www:/usr/local/apache2/htdocs/:Z"
      # - "/opt/showroom/content/gh-pages:/usr/local/apache2/htdocs/:Z"
      - ./www:/opt/app-root/src # :Z
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - ./www:/usr/share/nginx/html

  terminal-01:
    image: docker.io/tonykay/service-rhel-8-terminal-base
    container_name: terminal-01
    hostname: terminal-01
    command: butterfly.server.py --host=localhost --port=8888 --unsecure --i-hereby-declare-i-dont-want-any-security-whatsoeverc
    ports:
      - "8001:8888"

  terminal-02:
    image: docker.io/tonykay/service-rhel-8-terminal-base
    container_name: terminal-02
    hostname: terminal-02
    ports:
      - "8002:8888"


  jupyter:
    image: docker.io/jupyter/scipy-notebook
    container_name: jupyter
    hostname: jupyter
    ports:
      - "8004:8888"

  codeserver:
    image: docker.io/codercom/code-server
    container_name: codeserver
    hostname: codeserver
    environment:
      - PASSWORD=changeme
    ports:
      - "8088:8080"
        # old style - env var better e.g. PASSWORD
    # volumes:
    #   - "./config/code-server:/home/coder/.config/code-server"

        # RHDP codeserver
        #
        # image: quay.io/gpte-devops-automation/codeserver #docker.io/codercom/code-server
        # platform: linux/amd64

        # volumes:
        # - ".:/home/coder"
        # -u "$(id -u):$(id -g)" \
