---

networks:
  default:
      name: example.com

services:

  lab-terminal:
    image: docker.io/tonykay/service-rhel-8-terminal-base
    container_name: lab-terminal
    hostname: lab-terminal
    ports:
      - "8000:8888"        # Browser based terminal session

  lab-httpd:
    image: registry.redhat.io/rhel8/httpd-24
    container_name: lab-httpd
    hostname: lab-httpd
    volumes:
      - "./lab-html-content:/var/www/html"   # :z,ro"
    ports:
      - "80:8080"

...
