---
version: "3"

networks:
  default:
    name: showroom.example.com

services:

  web:
    image: registry.redhat.io/rhel9/nginx-122
    container_name: web
    hostname: web
    command: nginx -g "daemon off;"
    ports:
      - "8000:8080"
    volumes:
      - ./www:/opt/app-root/src:Z 

  codeserver:
    image: docker.io/codercom/code-server
    container_name: codeserver
    hostname: codeserver
    environment:
      - PASSWORD=changeme
    ports:
      - "8088:8080"
