---
version: "3"

networks:
  default:
    name: showroom.example.com

services:

  web:
    image: registry.redhat.io/rhel9/nginx-122
    container_name: web
    hostname: web
    command: nginx -g "daemon off;"
    ports:
      - "8000:8080"
    volumes:
      - ./www:/opt/app-root/src # :Z
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    # image: nginx
      # - "8000:80"
      # - ./www:/usr/share/nginx/html

  # terminal-01:
  #   image: docker.io/tonykay/service-rhel-8-terminal-base
  #   container_name: terminal-01
  #   hostname: terminal-01
  #   ports:
  #     - "8001:8888"
  #
  # terminal-02:
  #   image: docker.io/tonykay/service-rhel-8-terminal-base
  #   container_name: terminal-02
  #   hostname: terminal-02
  #   ports:
  #     - "8002:8888"

  codeserver:
    image: docker.io/codercom/code-server
    container_name: codeserver
    hostname: codeserver
    environment:
      - PASSWORD=changeme
    ports:
      - "8088:8080"
        # old style - env var better e.g. PASSWORD
    # volumes:
    #   - "./config/code-server:/home/coder/.config/code-server"

        # RHDP codeserver
        #
        # image: quay.io/gpte-devops-automation/codeserver #docker.io/codercom/code-server
        # platform: linux/amd64
    
        # volumes:
        # - ".:/home/coder"
        # -u "$(id -u):$(id -g)" \
