---

- name: Listen for events on a webhook
  hosts: all

  sources:

    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8000

  rules:

    - name: Run Module 1 Grader
      condition: event.payload.action == "Check Me"
        and event.payload.module == 1
      action:
        run_playbook:
          name: check-module-1.yml

    - name: Run Module 2 Grader
      condition: event.payload.action == "Check Me"
        and event.payload.module == 2
      action:
        run_playbook:
          name: check-module-2.yml
